### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/jnxlibc#57]
Two tests have been commented out after they started failing, likely to be related to my change of types used in the framework.

The offenders are test_negative_stream_listen_scenario & the one that comes after from jnx_unixsocket.c  (The tests fail via timing out) 

Mind taking a look?

![screen shot 2015-01-09 at 20 18 57](https://cloud.githubusercontent.com/assets/1235925/5690831/e5b1ea98-989d-11e4-8a5e-647bfb0fe7b2.png)

**Comment by draganglumac** [comment]
i'll have a looksee now

**Comment by draganglumac** [comment]
Got it.

I've had to introduce another type to jnxtypes for ssize_t (signed size_t), becuase the read call was returning -1 in read_stream_socket, but since jnx_size is unsigned integer it was being interpreted as 0xfffffffffffffffff (all 1s) which is -1 in signed int interpretation.

A subtle bug. Anyways it's fixed now.
