### ISSUE TITLE
Latest merge breaks tcp listening on local machine

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/jnxlibc#67]

**Comment by draganglumac** [comment]
I don't think it was the latest merge :( TCP comms seem well busted...

The problem is that read call blocks waiting for input on a an open socket. So unless you close socket in tcp_send it will keep hanging. If you do however close that socket you have to recreate a new one (you can't reconnect on it).

I think we might have to devise a solution where if the connection is established on a send socket (yet to investigate how to detect it) we don't try to connect again but instead just send on the existing connection. But also we need to spawn a separate thread for this connection in listen - so a fairly fundamental redesign I suppose :(

The tests for listen only connect and send once and then close the connection so this was an undetected problem. If you try wait a second and send another packet on the same socket it will hang or fail with socket already connected.

I can try and do this create worker thread for each now connection this morning. Feeling a bit better so will give it a go in a separate branch in jnxlibc.

**Comment by AlexsJones** [comment]
I also came to the conclusion it's not the merge.

I've written two test programs that work fine on the same machine with tcp_send() and tcp_listen() as I'd expect.

In Whisper,
The error message I'm seeing is 'Connection refused' so that's before it hits the read. 
i know I'm using _with_receipts() but even removing that it's borked.

**Comment by AlexsJones** [comment]
```
jnx_size jnx_socket_tcp_send(jnx_socket *s, jnx_char *host, jnx_char* port, jnx_uint8 *msg, jnx_size msg_len) {
JNXCHECK(s);
JNXCHECK(host);
JNXCHECK(port);
JNXCHECK(msg);
JNXCHECK(msg_len);
JNXCHECK(s->isclosed == 0);
JNXCHECK(s->stype == SOCK_STREAM);
struct addrinfo hints, *res;
memset(&hints,0,sizeof(hints));
hints.ai_family = s->addrfamily;
hints.ai_socktype = s->stype;
jnx_int32 rg = 0;
if((rg = getaddrinfo(host,port,&hints,&res)) != 0) {
JNX_LOG(DEFAULT_CONTEXT,"%s\n",gai_strerror(rg));
return 0;
}
if(connect(s->socket,res->ai_addr,res->ai_addrlen) != 0) {
perror("connect:");
freeaddrinfo(res);
return 0;
}
```
This is the code I'm hitting in whisper as an experiment (Not using read receipts until we figure this)
Now for some reason as I mentioned in whisper on the same machine i cant connect to myself.
But I cant in the test program.
I'm going to double check my socket but here is a gist of the code in progress

https://gist.github.com/AlexsJones/f1dbd15898dc9f797452

**Comment by draganglumac** [comment]
ok i've changed how we handle tcp in tcp_send and tcp_listen
changed the tests for tcp4 and tcp6 listens to send multiple packets too
see if this fixes it
travis just running now

**Comment by draganglumac** [comment]
ok tests passed on travis, you can merge it now

**Comment by AlexsJones** [comment]
Great work thanks for this.. I am just looking at the code to understand what you've done.
